# Bibliotecas
- Numpy
- Pandas
- Matplotlib
- Logging um interesse transversal

## Numpy
lingua franca para troca de dados

- **ndarray** -> array multidimensional eficar que oferece operações aritméticas rápidas, orientadas a arrays.
- **funções matemáticas** -> para operações rápidas em arrays
- ferramentas para ler e escrever dados de array em disco e trabalhar com **arquivos mapeados** em memória.
- recursos de **álgebra linear**
- **API para linguagem C**

### Para análise de dados
- **operações rápidas em arrays**
- **algoritmos comuns para arrays**
- **estatísticas descritivas**

## Numpy

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)
data

array([[-0.46570134,  0.73217499, -1.38419704],
       [ 1.41417863, -0.74682615,  1.23392844]])

In [3]:
data * 10

array([[ -4.65701338,   7.32174988, -13.84197043],
       [ 14.14178628,  -7.46826151,  12.33928442]])

In [4]:
data + data

array([[-0.93140268,  1.46434998, -2.76839409],
       [ 2.82835726, -1.4936523 ,  2.46785688]])

In [5]:
data.shape

(2, 3)

In [6]:
data * data

array([[0.21687774, 0.53608021, 1.91600145],
       [1.99990119, 0.5577493 , 1.5225794 ]])

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[6]

6

In [9]:
arr[5:8]

array([5, 6, 7])

In [10]:
data[1][0]

1.4141786276747492

In [11]:
data.T

array([[-0.46570134,  1.41417863],
       [ 0.73217499, -0.74682615],
       [-1.38419704,  1.23392844]])

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [14]:
data2 = np.random.rand(2,3)
data2

array([[0.0934875 , 0.0965785 , 0.09159764],
       [0.76368033, 0.27840188, 0.67671148]])

In [15]:
data3 = np.maximum(data, data2)
data3

array([[0.0934875 , 0.73217499, 0.09159764],
       [1.41417863, 0.27840188, 1.23392844]])

## Pandas
Estilo idiomático do numpy

In [17]:
import pandas as pd
import sqlite3 as sql

In [18]:
df_cardio = pd.read_json('cardio.json')
df_cardio

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    117       175     282.4
4        60    102       148     406.0
5        30     98       127     300.0