# Bibliotecas
- Numpy
- Pandas
- Matplotlib
- Logging um interesse transversal

## Numpy
lingua franca para troca de dados

- **ndarray** -> array multidimensional eficar que oferece operações aritméticas rápidas, orientadas a arrays.
- **funções matemáticas** -> para operações rápidas em arrays
- ferramentas para ler e escrever dados de array em disco e trabalhar com **arquivos mapeados** em memória.
- recursos de **álgebra linear**
- **API para linguagem C**

### Para análise de dados
- **operações rápidas em arrays**
- **algoritmos comuns para arrays**
- **estatísticas descritivas**

## Numpy

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)
data

array([[-1.06626032, -0.55036673, -0.69381056],
       [-0.6253521 , -0.98401696,  0.95892844]])

In [3]:
data * 10

array([[-10.66260316,  -5.50366727,  -6.93810559],
       [ -6.25352101,  -9.84016956,   9.58928445]])

In [4]:
data + data

array([[-2.13252063, -1.10073345, -1.38762112],
       [-1.2507042 , -1.96803391,  1.91785689]])

In [5]:
data.shape

(2, 3)

In [6]:
data * data

array([[1.13691106, 0.30290353, 0.48137309],
       [0.39106525, 0.96828937, 0.91954376]])

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[6]

6

In [9]:
arr[5:8]

array([5, 6, 7])

In [10]:
data[1][0]

-0.625352101154618

In [11]:
data.T

array([[-1.06626032, -0.6253521 ],
       [-0.55036673, -0.98401696],
       [-0.69381056,  0.95892844]])

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [14]:
data2 = np.random.rand(2,3)
data2

array([[0.64991198, 0.15700277, 0.85788602],
       [0.81531356, 0.90533193, 0.78696675]])

In [15]:
data3 = np.maximum(data, data2)
data3

array([[0.64991198, 0.15700277, 0.85788602],
       [0.81531356, 0.90533193, 0.95892844]])

## Pandas
Estilo idiomático do numpy

In [16]:
import pandas as pd
import sqlite3 as sql

In [57]:
df_cardio = pd.read_json('cardio.json')
df_cardio

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135       NaN
3        45    117       175     282.4
4        60    102       148     406.0
5        30     98       127     300.0

In [19]:
type(df_cardio)

pandas.core.frame.DataFrame

In [20]:
type(df_cardio['Duration'])

pandas.core.series.Series

In [21]:
type(df_cardio.index)

pandas.core.indexes.base.Index

In [22]:
df_cardio.head()

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    117       175     282.4
4        60    102       148     406.0

In [25]:
df_cardio.tail()

Duration  Pulse  Maxpulse  Calories
1        60    117       145     479.0
2        60    103       135     340.0
3        45    117       175     282.4
4        60    102       148     406.0
5        30     98       127     300.0

In [23]:
df_cardio.Calories

0    409.1
1    479.0
2    340.0
3    282.4
4    406.0
5    300.0
Name: Calories, dtype: float64

In [30]:
# df_cardio * 3
# df_cardio / 2
df_cardio + df_cardio

Duration  Pulse  Maxpulse  Calories
0       120    220       260     818.2
1       120    234       290     958.0
2       120    206       270     680.0
3        90    234       350     564.8
4       120    204       296     812.0
5        60    196       254     600.0

In [36]:
df_cardio.drop(columns=['Maxpulse'])

Duration  Pulse  Calories
0        60    110     409.1
1        60    117     479.0
2        60    103     340.0
3        45    117     282.4
4        60    102     406.0
5        30     98     300.0

In [38]:
df_cardio.describe()

Duration       Pulse    Maxpulse    Calories
count    6.0000    6.000000    6.000000    6.000000
mean    52.5000  107.833333  143.333333  369.416667
std     12.5499    8.084965   17.557525   75.070005
min     30.0000   98.000000  127.000000  282.400000
25%     48.7500  102.250000  131.250000  310.000000
50%     60.0000  106.500000  140.000000  373.000000
75%     60.0000  115.250000  147.250000  408.325000
max     60.0000  117.000000  175.000000  479.000000

In [43]:
df_cardio.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  6 non-null      int64  
 1   Pulse     6 non-null      int64  
 2   Maxpulse  6 non-null      int64  
 3   Calories  5 non-null      float64
dtypes: float64(1), int64(3)
memory usage: 240.0 bytes


In [58]:
# df_cardio['Calories'] = df_cardio['Calories'].fillna(0)
df_cardio['Calories'] = df_cardio['Calories'].fillna(df_cardio['Calories'].mean())
df_cardio.info()


<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  6 non-null      int64  
 1   Pulse     6 non-null      int64  
 2   Maxpulse  6 non-null      int64  
 3   Calories  6 non-null      float64
dtypes: float64(1), int64(3)
memory usage: 240.0 bytes


In [60]:
df_cardio.corr()

Duration     Pulse  Maxpulse  Calories
Duration  1.000000  0.310450  0.013615  0.790073
Pulse     0.310450  1.000000  0.634487  0.246319
Maxpulse  0.013615  0.634487  1.000000 -0.285498
Calories  0.790073  0.246319 -0.285498  1.000000

In [61]:
df_cardio.corr('spearman')

Duration     Pulse  Maxpulse  Calories
Duration  1.000000  0.257248  0.169031  0.777542
Pulse     0.257248  1.000000  0.550782  0.231908
Maxpulse  0.169031  0.550782  1.000000 -0.142857
Calories  0.777542  0.231908 -0.142857  1.000000

In [62]:
df_cardio.cov()

Duration       Pulse    Maxpulse  Calories
Duration     157.5   31.500000    3.000000   730.500
Pulse         31.5   65.366667   90.066667   146.720
Maxpulse       3.0   90.066667  308.266667  -369.300
Calories     730.5  146.720000 -369.300000  5427.824

#### Lendo CSV


In [83]:
df_ibov = pd.read_csv('./IBOVDia_18-06-24.csv', sep=';', skiprows=1, encoding='latin-1', index_col=False)
df_ibov.drop(df_ibov.index[-2:], inplace=True)
df_ibov.tail()


Código         Ação        Tipo  Qtde. Teórica Part. (%)
81  VAMO3        VAMOS  ON      NM    498.860.020     0,180
82  VBBR3        VIBRA  ON      NM  1.114.613.709     1,147
83  VIVA3  VIVARA S.A.  ON      NM    125.912.025     0,128
84  WEGE3          WEG  ON      NM  1.482.105.837     2,930
85  YDUQ3   YDUQS PART  ON      NM    289.347.914     0,159

In [85]:
df_ibov.rename(columns={
    'Código': 'codigo',
    'Ação': 'acao',
    'Tipo': 'tipo',
    'Qtde. Teórica': 'qtde_teorica', 
    'Part. (%)': 'participacao'},
    inplace=True)

In [86]:
df_ibov

codigo          acao        tipo   qtde_teorica participacao
0   RRRP3  3R PETROLEUM  ON      NM    238.441.689        0,310
1   ALOS3         ALLOS  ON      NM    532.616.595        0,561
2   ALPA4    ALPARGATAS  PN      N1    166.362.038        0,076
3   ABEV3     AMBEV S/A          ON  4.394.245.879        2,518
4   ARZZ3     AREZZO CO  ON      NM     62.305.891        0,160
..    ...           ...         ...            ...          ...
81  VAMO3         VAMOS  ON      NM    498.860.020        0,180
82  VBBR3         VIBRA  ON      NM  1.114.613.709        1,147
83  VIVA3   VIVARA S.A.  ON      NM    125.912.025        0,128
84  WEGE3           WEG  ON      NM  1.482.105.837        2,930
85  YDUQ3    YDUQS PART  ON      NM    289.347.914        0,159

[86 rows x 5 columns]