# Bibliotecas
- Numpy
- Pandas
- Matplotlib
- Logging um interesse transversal

## Numpy
lingua franca para troca de dados

- **ndarray** -> array multidimensional eficar que oferece operações aritméticas rápidas, orientadas a arrays.
- **funções matemáticas** -> para operações rápidas em arrays
- ferramentas para ler e escrever dados de array em disco e trabalhar com **arquivos mapeados** em memória.
- recursos de **álgebra linear**
- **API para linguagem C**

### Para análise de dados
- **operações rápidas em arrays**
- **algoritmos comuns para arrays**
- **estatísticas descritivas**

## Numpy

In [3]:
import numpy as np

In [27]:
data = np.random.randn(2,3)
data

array([[-1.09968482,  0.67559514,  0.08071831],
       [-0.07782806, -1.13181008,  1.0635213 ]])

In [16]:
data * 10

array([[  6.28918949,  -0.69434481,  -7.72960765],
       [  4.71618251,   8.0433052 , -19.00653755]])

In [17]:
data + data

array([[ 1.2578379 , -0.13886896, -1.54592153],
       [ 0.9432365 ,  1.60866104, -3.80130751]])

In [21]:
data.shape

(2, 3)

In [19]:
data * data

array([[0.39553904, 0.00482115, 0.59746834],
       [0.22242378, 0.64694759, 3.6124847 ]])

In [23]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[6]

np.int64(6)

In [25]:
arr[5:8]

array([5, 6, 7])

In [30]:
data[1][0]

np.float64(0.5242977551876434)

In [32]:
data.T

array([[-0.04005652,  0.52429776],
       [-1.31623492,  0.17856716],
       [ 1.51882333,  0.39220135]])

In [33]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [35]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [37]:
data2 = np.random.rand(2,3)
data2

array([[0.71975382, 0.96089507, 0.97832825],
       [0.7245038 , 0.39338889, 0.40284576]])

In [38]:
data3 = np.maximum(data, data2)
data3

array([[0.71975382, 0.96089507, 1.51882333],
       [0.7245038 , 0.39338889, 0.40284576]])

## Pandas
Estilo idiomático do numpy